export const services = [
  {
    id: 1,
    carType: "SEDAN",
    serviceType: "PROTECTION FILM",
    serviceName: "Paint Protection film (Half front)",
    priceBefore: 1990,
    priceAfter: 1590,
  },
  {
    id: 2,
    carType: "SEDAN",
    serviceType: "PROTECTION FILM",
    serviceName: "Paint Protection film (Full front)",
    priceBefore: 3990,
    priceAfter: 3190,
  },
  {
    id: 3,
    carType: "SEDAN",
    serviceType: "PROTECTION FILM",
    serviceName: "Paint Protection film (Brigh Full Body)",
    priceBefore: 11990,
    priceAfter: 9590
  },
  {
    id: 4,
    carType: "SEDAN",
    serviceType: "PROTECTION FILM",
    serviceName: "Paint Protection film  (MAT Full Body)",
    priceBefore: 13990,
    priceAfter: 11190,
  },
  {
    id: 5,
    carType: "SEDAN",
    serviceType: "Window Film",
    serviceName: "Thermal Tint",
    priceBefore: 1090,
    priceAfter: 890,
  },
  {
    id: 6,
    carType: "SEDAN",
    serviceType: "Window Film",
    serviceName: "Windshield Protection",
    priceBefore: 1090,
    priceAfter: 890,
  },
  {
    id: 7,
    carType: "SEDAN",
    serviceType: "Polishing",
    serviceName: "Full Polishing",
    priceBefore: 990,
    priceAfter: 790,
  },
  {
    id: 8,
    carType: "SEDAN",
    serviceType: "Polishing",
    serviceName: "Exterior Polish",
    priceBefore: 790,
    priceAfter: 590,
  },
  {
    id: 9,
    carType: "SEDAN",
    serviceType: "Nano Ceramic",
    serviceName: "Full Nano Ceramic",
    priceBefore: 1990,
    priceAfter: 1590,
  },
  {
    id: 10,
    carType: "SEDAN",
    serviceType: "Nano Ceramic",
    serviceName: "Exterior Nano Cermaic",
    priceBefore: 990,
    priceAfter: 790,
  },
  {
    id: 11,
    carType: "SEDAN",
    serviceType: "Nano Ceramic",
    serviceName: "Interior Nano Cermaic",
    priceBefore: 1190,
    priceAfter: 990,
  },
  {
    id: 12,
    carType: "SUV",
    serviceType: "PROTECTION FILM",
    serviceName: "Paint Protection film (Half front)",
    priceBefore: 2390,
    priceAfter: 1990,
  },
  {
    id: 13,
    carType: "SUV",
    serviceType: "PROTECTION FILM",
    serviceName: "Paint Protection film (Full front)",
    priceBefore: 4590,
    priceAfter: 3690,
  },
  {
    id: 14,
    carType: "SUV",
    serviceType: "PROTECTION FILM",
    serviceName: "Paint Protection film (Brigh Full Body)",
    priceBefore: 13990,
    priceAfter: 1190
  },
  {
    id: 15,
    carType: "SUV",
    serviceType: "PROTECTION FILM",
    serviceName: "Paint Protection film  (MAT Full Body)",
    priceBefore: 15990,
    priceAfter: 12790,
  },
  {
    id: 16,
    carType: "SUV",
    serviceType: "Window Film",
    serviceName: "Thermal Tint",
    priceBefore: 1290,
    priceAfter: 1090,
  },
  {
    id: 17,
    carType: "SUV",
    serviceType: "Window Film",
    serviceName: "Windshield Protection",
    priceBefore: 1090,
    priceAfter: 890,
  },
  {
    id: 18,
    carType: "SUV",
    serviceType: "Polishing",
    serviceName: "Full Polishing",
    priceBefore: 1090,
    priceAfter: 890,
  },
  {
    id: 19,
    carType: "SUV",
    serviceType: "Polishing",
    serviceName: "Exterior Polish",
    priceBefore: 890,
    priceAfter: 690,
  },
  {
    id: 20,
    carType: "SUV",
    serviceType: "Nano Ceramic",
    serviceName: "Full Nano Ceramic",
    priceBefore: 2190,
    priceAfter: 1790,
  },
  {
    id: 21,
    carType: "SUV",
    serviceType: "Nano Ceramic",
    serviceName: "Exterior Nano Cermaic",
    priceBefore: 1090,
    priceAfter: 890,
  },
  {
    id: 22,
    carType: "SUV",
    serviceType: "Nano Ceramic",
    serviceName: "Interior Nano Cermaic",
    priceBefore: 1290,
    priceAfter: 1090,
  },
];

