import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

// Import the Roboto font
const roboto = Roboto({
  variable: "--font-roboto", // Define a CSS variable for the font
  subsets: ["latin"], // Include Latin subset
  weight: ["400", "500", "700"], // Specify font weights you want to include
});

export const metadata: Metadata = {
  title: "Booking Page",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages=await getMessages()
  return (
    <html lang={locale}>
      <body
        className={`${roboto.variable}`} // Use the Roboto variable
        suppressHydrationWarning
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}