import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/booking/Footer";

// Import the Roboto font
const roboto = Roboto({
  variable: "--font-roboto", // Define a CSS variable for the font
  subsets: ["latin"], // Include Latin subset
  weight: ["400", "500", "700"], // Specify font weights you want to include
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased min-h-screen bg-gray-100`} // Use the Roboto variable
        suppressHydrationWarning
      >
        {children}
        <Footer/>
      </body>
    </html>
  );
}